name = "QuantumRegistry"
uuid = "284f5efa-4f8a-42cb-83fd-c2613f18f741"
repo = "git@github.com:jlapeyre/QuantumRegistry.git"
description = "A few quantum packages"

[packages]
7d983096-c313-11eb-0b95-579bee092dbe = { name = "SparseArraysN", path = "S/SparseArraysN" }
8d55b643-9899-48dd-ae5e-3f792c55f725 = { name = "QiskitQuantumInfo", path = "Q/QiskitQuantumInfo" }
d0cc4389-ef80-471f-8a8c-dd305d114ada = { name = "QuantumOps", path = "Q/QuantumOps" }
f7ec468b-4310-4c77-90aa-f73697106762 = { name = "ElectronicStructure", path = "E/ElectronicStructure" }
