name = "QuantumRegistry"
uuid = "284f5efa-4f8a-42cb-83fd-c2613f18f741"
repo = "git@github.com:jlapeyre/QuantumRegistry.git"
description = "A few quantum packages"

[packages]
8d55b643-9899-48dd-ae5e-3f792c55f725 = { name = "QiskitQuantumInfo", path = "Q/QiskitQuantumInfo" }
